builders:
  # name of the builder
  analyzer_generator:
    # library URI containing the builder - maps to `lib/member_count_library_generator.dart`
    import: "package:element_tree_console/builder.dart"
    # Name of the function in the above library to call.
    builder_factories: ["metadataLibraryBuilder"]
    # The mapping from the source extension to the generated file extension
    build_extensions: {".dart": [".analyzer.dart"]}
    # Will automatically run on any package that depends on it
    auto_apply: dependents
    # Generate the output directly into the package, not to a hidden cache dir
    build_to: source

targets:
  $default:
    builders:
      element_tree_console|analyzer_generator:
        generate_for:
          - lib/src/metadata.dart