name: element_tree_console
description: A console application used to traverse the analyzer elements of a Dart file.
version: 0.0.1
repository: https://github.com/jodinathan/element_tree_viewer/tree/main/element_tree_console

environment:
  sdk: ^3.2.0

dev_dependencies:
  lints: any
  test: ^1.24.0
  build_runner: ^2.4.7

dependencies:
  analyzer: ^6.3.0
  collection: ^1.18.0
  ackable: ^0.0.1
  code_builder: ^4.5.0-dev
  source_gen: ^1.5.0
  dart_style: ^2.3.4
  build: ^2.4.1

dependency_overrides:
  code_builder:
   git: https://github.com/jodinathan/code_builder
  analyzer: ^6.3.0